name: Python application

on: [ push ]

jobs:
  build:
    env:
      PIPENV_NO_INHERIT: 1
      PIPENV_IGNORE_VIRTUALENVS: 1
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python  3.10.11
        uses: actions/setup-python@v1
        with:
          python-version:  3.10.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv sync -d  

      - name: Rodar flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics        
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        run: |
          pytest libpythonpro --cov=libpythonpro

      - name: Relatório Coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          codecov
