name: Python application

on: [ push ]

jobs:
  build:
    env:
      PIPENV_NO_INHERIT: 1
      PIPENV_IGNORE_VIRTUALENVS: 1
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python  3.10.11
        uses: actions/setup-python@v1
        with:
          python-version:  3.10.11

      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt   

      - name: Rodar flake8
        uses: py-actions/flake8@v1
        with:
          checkName: 'flake8_py3'

      - name: Test with pytest
        run: |
          pytest libpythonpro --cov=libpythonpro

      - name: Relatório Coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          codecov
